version: '3'
services:
  dev-consul:
    image: consul:1.4.4
    container_name: dev-consul
    network_mode: host
  gamer-session1:
    image: cloudx/gamer-session-load-balanced
    container_name: gamer-session1
    network_mode: host
    environment:
      SERVER_PORT: 8002
  gamer-session2:
    image: cloudx/gamer-session-load-balanced
    container_name: gamer-session2
    network_mode: host
    environment:
      SERVER_PORT: 8003
  gamer-session3:
    image: cloudx/gamer-session-load-balanced
    container_name: gamer-session3
    network_mode: host
    environment:
      SERVER_PORT: 8004
  gamer-session4:
    image: cloudx/gamer-session-load-balanced
    container_name: gamer-session4
    network_mode: host
    environment:
      SERVER_PORT: 8005
  gamer-session5:
    image: cloudx/gamer-session-load-balanced
    container_name: gamer-session5
    network_mode: host
    environment:
      SERVER_PORT: 8006
  gamer-center:
    image: cloudx/gamer-center-load-balanced
    container_name: gamer-center
    network_mode: host
    environment:
      SERVER_PORT: 8001