version: '3'
services:
  dev-rabbit:
    image: rabbitmq:3.7-management
    network_mode: host
  gamer-creator:
    build: gamer-creator/
    container_name: gamer-creator
    network_mode: host
    environment:
      SERVER_PORT: 8002
  gamer-emailer:
    build: gamer-emailer/
    container_name: gamer-emailer
    network_mode: host
    environment:
      SERVER_PORT: 8001